export const FB_GET_PROFILE_DATA = 'FB/GET_PROFILE_DATA'
export const FB_GET_PROFILE_DATA_SUCCESS = 'FB/GET_PROFILE_DATA_SUCCESS'
export const FB_GET_PROFILE_DATA_FAILED = 'FB/GET_PROFILE_DATA_FAILED'
